### ISSUE TITLE
Fields Modal

### ISSUE THREAD

**Issue by wilsonge** [joomla/40-backend-template#326]
The com_fields modal got reworked totally. I've taken the new version and I've edited some of the key classes to the bs4 equivalents. But i haven't checked it and it's almost certainly broken. Go do you're awesomeness to it

https://github.com/joomla/joomla-cms/blob/4.0-dev/administrator/components/com_fields/views/fields/tmpl/modal.php

**Comment by C-Lodder** [comment]
@ciar4n was this ever done? If you have J4 fired up, could you quickly see if the modal works in com_fields?

**Comment by ciar4n** [comment]
Closing as suggested by by @C-Lodder (skype)
