### ISSUE TITLE
[new design] List view - Sort direction indicator

### ISSUE THREAD

**Issue by ciar4n** [joomla/40-backend-template#345]
Currently when you sort by a particular column, the sort direction is indicated by a directional arrow...

![image](https://user-images.githubusercontent.com/2803503/36546219-c5f13160-17e2-11e8-9c30-9c032b523faf.png)

New design icons are non directional.. they don't specify a particular direction. Revert to using the old caret icons?

![image](https://user-images.githubusercontent.com/2803503/36546406-3dc3f7fe-17e3-11e8-8040-639b83a926cf.png)

**Comment by svom** [comment]
Hey @ciar4n ,

works better for me - you're right.

**Comment by ciar4n** [comment]
PR created... https://github.com/joomla/40-backend-template/pull/346
