### ISSUE TITLE
[new design] Button accessibility - focus

### ISSUE THREAD

**Issue by brianteeman** [joomla/40-backend-template#347]
Try to tab between toolbar buttons and you will see that there is no visible indicator of which button you are on except for the search and table options

I am NOT a css expert but it looks like there is something resetting the outline on the active state

**Comment by C-Lodder** [comment]
Is this with the open PR or current state?

**Comment by ciar4n** [comment]
Seems to be overridden by the button box-shadow of the design. I'll fix it later.

**Comment by ciar4n** [comment]
Thank you @brianteeman

**Comment by ciar4n** [comment]
PR created... #352
