### ISSUE TITLE
Change sidebar icon on toggle

### ISSUE THREAD

**Issue by ciar4n** [joomla/40-backend-template#350]
'Toggle Menu' icon should probably change between open and closed..

![image](https://user-images.githubusercontent.com/2803503/36643566-2388be42-1a45-11e8-9b4f-e159f2cf57f1.png)

**Comment by brianteeman** [comment]
Also (at least on chrome for windows) when toggled you can still see the first pixels of the T

**Comment by svom** [comment]
Icon should change - definitely

**Comment by lakhanmandloi** [comment]
@ciar4n Thank you :) I think we should close this issue now.
