### ISSUE TITLE
long component names

### ISSUE THREAD

**Issue by brianteeman** [joomla/40-backend-template#357]
Because the menu name is indented when it wraps it looks odd. See components -> post installation messages

**Comment by brianteeman** [comment]
<img width="264" alt="firefox_2018-02-27_16-24-31" src="https://user-images.githubusercontent.com/1296369/36740671-0e24c4d2-1bdb-11e8-96bc-fa9af7cf1cbc.png">

**Comment by C-Lodder** [comment]
PR: https://github.com/joomla/40-backend-template/pull/362
