### ISSUE TITLE
Switcher custom field

### ISSUE THREAD

**Issue by brianteeman** [joomla/40-backend-template#359]
In some places it isnt showing. Dont know why

This is the integrations tab of the articles component options

<img width="605" alt="firefox_2018-02-27_16-26-31" src="https://user-images.githubusercontent.com/1296369/36740741-3da06644-1bdb-11e8-97a2-85f02d9db842.png">

**Comment by C-Lodder** [comment]
This PR fixes the issue: https://github.com/joomla/joomla-cms/pull/19296
