### ISSUE TITLE
[new design] [menu] B/C break moving 3rd level to 'dashboard' view

### ISSUE THREAD

**Issue by ciar4n** [joomla/40-backend-template#367]
The proposed design moves 3rd level menu items from the menu to a new 'dashboard' style view....

As I see it this create a B/C break for components. Because there's no third level on the new sidebar, any Joomla 3 component that has one will be required to restructure their XML to cater for J4. A new 'dashboard' view will also have to be created to accommodate the 3rd level items. 

To my knowledge there has been no public discussion on this. It seems like a significant change to be implementing without some wider agreement.

Personally I believe the idea certainly has it's merits, I am not sure if it adds enough to warrant the b/c break.

**Comment by brianteeman** [comment]
1. Is it possible to do some magic at runtime to convert old style level 3 to a basic dashboard style ie big buttons with just the text

or

2. Support old style level 3 but convert all core to new style dashboard

**Comment by ciar4n** [comment]
1. So prepend the items to the default view of the component?  

2. I guess this would work. It means bringing back a 3rd level to the menu. Not sure how we want to implement this. The most common option for multilevel menus is an accordion.

**Comment by brianteeman** [comment]
1. I was thinking off something like this https://magazine.joomla.org/media/k2/galleries/3289/Settings%20-%20Initial.png

**Comment by ciar4n** [comment]
We can style the 3rd level to fill the screen in this manner. Would this look ok considering some components will only have a small number of 3rd level menu items? In J3 these would be uncategorised. Admittedly I am not entirely convinced how well this is gonna work but I am willing to give it a try. I guess it just feels messy.

**Comment by dgt41** [comment]
> We can style the 3rd level to fill the screen in this manner

The menu logic just for the accessibility is quite big and complicated. Adding more sugar on top of it will make it really hard to maintain...

my 2c here

**Comment by coolcat-creations** [comment]
- The dashboard view is the second level not the third.
- Just for the Help Page and the Settings Page it did not make a lot of sense to put everything into the submenu.
- Third Level is supposed to be in the dashboard of the Components

**Comment by ciar4n** [comment]
There has been a bit of confusion here. On further discussion with @coolcat-creations, we have been able to clarify that these dashboard views are only been added to some of the core components (com_content, com_users, com_menus) and not as a rule to every component.
