### ISSUE TITLE
[new design] notifications display problem

### ISSUE THREAD

**Issue by svom** [joomla/40-backend-template#374]
The Notifications are overlayed by the headerbar (see screenshot). 

Need to fix the z-index.

Brwoser: Google Chrome Version 65.0.3325.181

![bildschirmfoto 2018-04-16 um 14 21 10](https://user-images.githubusercontent.com/14434412/38810452-1874f9b2-4187-11e8-818c-a0d05e86863b.png)

**Comment by brianteeman** [comment]
is this already foxed by #372

**Comment by svom** [comment]
Oh, didn't saw that, sorry. Perfect. thank you.

**Comment by brianteeman** [comment]
can you close it then please
