### ISSUE TITLE
[new design] decrease font-size for legend-tags

### ISSUE THREAD

**Issue by svom** [joomla/40-backend-template#380]
I would recommend to increase the font-size for the legends from 1.5rem to 1.1rem and increase the font-weight to 700.

The font-weight gives enough contrast to highlight the legend tags (see screenshot attached). No need for such huge legends.

improved:
![bildschirmfoto 2018-04-16 um 15 30 54](https://user-images.githubusercontent.com/14434412/38812020-6c6b1462-418b-11e8-9979-ddc55fa1fa7e.png)

current:
![bildschirmfoto 2018-04-16 um 15 30 35](https://user-images.githubusercontent.com/14434412/38812021-6c832656-418b-11e8-8b0d-7f7aa5d9f692.png)

**Comment by ciar4n** [comment]
PR created... #388
