### ISSUE TITLE
[new design] missing styles for list-view

### ISSUE THREAD

**Issue by svom** [joomla/40-backend-template#382]
The styles for the list-view of items (articles, menus etc.) are missing. I attached a screenshot of the design-proposal published in joomla-magazine.

I know it's not exactly the same view but the general layout is the same.

Current:
![image](https://user-images.githubusercontent.com/14434412/38812346-5ccf713c-418c-11e8-832c-c0c494872e1b.png)

Proposal:
![image](https://user-images.githubusercontent.com/14434412/38812363-61d5442c-418c-11e8-8fdc-6ad27ed0657e.png)

![image](https://user-images.githubusercontent.com/14434412/38812415-84477872-418c-11e8-90ba-4ff3b8a0d152.png)

**Comment by ciar4n** [comment]
Could you have a look at com_content -> Articles as this is the only view styled per the new design. There is a bit of work involved changing all the views. If you are happy with that I will start amending the rest.

**Comment by svom** [comment]
@ciar4n Problem is, that I'm not able to create an article. Getting an error each time.

**Comment by ciar4n** [comment]
PR created #396
