### ISSUE TITLE
[new design] design-proposal: for joomla-release-newsfeed

### ISSUE THREAD

**Issue by svom** [joomla/40-backend-template#383]
I would recommend to use the box-like styling used throughout the whole UI also for the joomla-release-newsfeed. 
Current:
![image](https://user-images.githubusercontent.com/14434412/38812842-aeae19e4-418d-11e8-810d-edb36afe1c32.png)

Recommended:
![image](https://user-images.githubusercontent.com/14434412/38812845-b24773f2-418d-11e8-9bed-40271cf98834.png)

**Comment by ciar4n** [comment]
PR created.. #389
