### ISSUE TITLE
Sidebar display concept

### ISSUE THREAD

**Issue by micker** [joomla/40-backend-template#440]
i will ask a question about sidebar zone ...
not sure we need to keep this size only for a few link ...
its like a jump menu not sure that realy effective ?
We win Lot of place Less button
Before
![old](https://user-images.githubusercontent.com/2539440/40529670-3bc6ffe0-5ff6-11e8-8327-dae1fd4e3ea8.png)
After (juste a preview)
![sidebar-drop](https://user-images.githubusercontent.com/2539440/40529681-45cdef12-5ff6-11e8-869a-d81d548e6ea5.png)

**Comment by coolcat-creations** [comment]
Maybe we find another solution that does not need a second click to access the links?

**Comment by dgrammatiko** [comment]
There are already 2 PRs for this:
inline: https://github.com/joomla/joomla-cms/pull/19590
dropdown: https://github.com/joomla/joomla-cms/pull/19552

So we can close the issue here
