### ISSUE TITLE
Sidebar is pointless

### ISSUE THREAD

**Issue by lllopo** [joomla/40-backend-template#454]
I don't know how it is exactly called, but the content of the element with ID "j-sidebar-container" seems pointless. It basically repeats the deepest level of the current menu, wasting a huge amount of horizontal space in the process. Doesn't mentioning it is positioned in a very illogical way, under/inside the current item (having that it is not visually separated from main screen content, being below the current item toolbar etc.).

I'd rather suggest to remove it or if you find to be a necessary navigation aid - then remove it and add breadcrumbs. Eventually the breadcrumbs can even dropdown to expose the other items of the same level they are, when hovered/clicked, to speed up the navigation. This would save a lot of space for more relevant stuff.

**Comment by brianteeman** [comment]
Thanks for your comments but if you review the design (not the current code) you will see that it will be removed

**Comment by lllopo** [comment]
Oh, sorry about that, then.  Silly question, but where can I check how the final thing would look ?

**Comment by wilsonge** [comment]
For the record the prototype: https://projects.invisionapp.com/share/8SES9JLZB#/screens/266892155
